version: '2'
services:
  eko-bot-demo:
    image: 826057481178.dkr.ecr.ap-southeast-1.amazonaws.com/eko-bot-demo:latest
    restart: always
    command: npm start
    env_file: .env_vars
    ports:
      - 3800:8080
    volumes:
      - ./google-credential.json:/app/google-credential.json
      - ./logs:/app/logs
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: '5'
  eko-bot-demo-notify:
    image: 826057481178.dkr.ecr.ap-southeast-1.amazonaws.com/eko-bot-demo:latest
    restart: always
    command: node app_schedule.js
    env_file: .env_vars
    environment:
      EKO_OAUTH_CLIENT_ID: bot
      EKO_OAUTH_CLIENT_SECRET: bot_secret
    volumes:
      - ./google-credential.json:/app/google-credential.json
      - ./logs:/app/logs
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: '5'
